name = "enervoid"
languageCode = 'en-US'
license = "MIT"
licenselink = "https://github.com/Enerhim/enervoid-theme/blob/main/LICENSE"
description = "A dark, minimal, lightweight theme for Hugo using Tailwind"
homepage = "https://github.com/Enerhim/enervoid-theme"
demosite = "https://enerhim.github.io/enervoid-demo/"

tags = ["blog", "minimal", "personal", "dark", "tailwind", "math", "katex", "personal", "clean", "code", "mermaid"]
features = ["syntax highlighting", "dark theme", "responsive design", "table of contents", "math"]

# If the theme has a single author
[author]
    name = "Himanshu Sharma"
    homepage = "https://enerhim.github.io/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
